### ISSUE TITLE
Issue with Heroku

### ISSUE THREAD

**Issue by WeirdSt1ng** [iamdowner/nhentai-telegram-bot#12]
I was hoping if you could help regarding with Heroku. Followed the pre-requisite and filled in the necessary token and database URL and Heroku returned a 'Postdeploy exit code was not 0' error. 

Unless I am genuinely stupid and missed something, is there anyway to fix this?

**Comment by sleroq** [comment]
Thank you for creating issue!

Fixed this problem [here](https://github.com/sleroq/nhentai-telegram-bot/commit/5bf453df452c1af951691d546182febd17957ec9), should work fine now.
