### ISSUE TITLE
English language

### ISSUE THREAD

**Issue by DiffUni** [iamdowner/nhentai-telegram-bot#13]
every time I put the English language and try to look for something, it always returns to the language previous to the one I had put in (to do some tests I saw that it does it only with English).
I don't know if it's just my problem but on other devices I find myself with the same thing. Now I try to see if it is only tied to my account but if it could be fixed the bot is perfect.

**Comment by sleroq** [comment]
Thanks for your report. I think I fixed it. There was no free space in the database.
