### ISSUE TITLE
How to deploy

### ISSUE THREAD

**Issue by winkxx** [iamdowner/nhentai-telegram-bot#6]
I hope to get some help on deployment, such as how to set it up in repl.it

**Comment by sleroq** [comment]
before deployment, make sure you have:
- mongo database (I'm using https://cloud.mongodb.com/ [guide on how to connect to your cluster](https://docs.atlas.mongodb.com/tutorial/connect-to-your-cluster/#connect-to-your-atlas-cluster))
- telegra.ph api token - https://telegra.ph/api#createAccount (example request - https://api.telegra.ph/createAccount?short_name=<some_username>&author_name=<some_username>)
- bot token - from @botFather

after you got it all:

Create new repl by cloning from iamdowner/nhentai-telegram-bot
create new file ".env" 
fill in:
BOT_TOKEN= <your token from BotFather>
REPL_URL=https://nhentai-telegram-bot.< your repl username >.repl.co
DATABASE_URL=< your mongo db >
TELEGRAPH_TOKEN=<telegra.ph api token>

**Comment by winkxx** [comment]
mongodb+srv://xxr:<password>@xrwink.zejyx.mongodb.net/<dbname>?retryWrites=true&w=majority Is it the format of database_url?

**Comment by sleroq** [comment]
> mongodb+srv://xxr:@xrwink.zejyx.mongodb.net/?retryWrites=true&w=majority Is it the format of database_url?

yes

**Comment by pseudokawaii** [comment]
@iamdowner did you drop repl.it support?

**Comment by sleroq** [comment]
> @iamdowner did you drop repl.it support?

No, I myself prefer repl.it over heroku.
If you want to host a bot on repl.it using webhook, you put your repl's domain as REPL_URL or HEROKU_URL in the env file.

**Comment by pseudokawaii** [comment]
@iamdowner yeah, i already tried and faced an error which seemed to be caused by not mentioning the port as PORT in the env. so i added the PORT and it worked. But there's another issue, the API and the other express get requests don't seem to be working, although the express server is running fine. do you have any idea how to fix that?

**Comment by sleroq** [comment]
> @iamdowner yeah, i already tried and faced an error which seemed to be caused by not mentioning the port as PORT in the env. so i added the PORT and it worked. But there's another issue, the API and the other express get requests don't seem to be working, although the express server is running fine. do you have any idea how to fix that?

in short, the problem with bot's api was that the bot was running on the same port as the api, [fixed it,](https://github.com/iamdowner/nhentai-telegram-bot/commit/819daa5939d58972be017c89284bce4bc86f6efd) so now it should work correctly
port bug fixed too, you don't have to add port to .env

**Comment by pseudokawaii** [comment]
@iamdowner I knew the issue was with API and bot webhook using the same port at the same time so i tried running the webhook with a different port only to find that repl.it doesn't allow opening multiple ports at the time. so this commit helps a lot, thank you.
