### ISSUE TITLE
Bot returns random manga.

### ISSUE THREAD

**Issue by pseudokawaii** [iamdowner/nhentai-telegram-bot#9]
I've deployed the bot successfully on Heroku. It's working as expected, the only issue is when I choose a manga in the inline mode (not from a search result but from the favorites or history menu), the bot sends a bunch of random manga and at the end, it sends the requested manga.

Here's the issue recorded as a GIF - https://i.imgur.com/0l8tZXN.gif

**Comment by sleroq** [comment]
Ok, this happens because the bot is trying to open any numbers it sees in your message. So this problem won't occur in other chats.
I will definitely fix it, but for now you can just replace username of my bot with the username of your bot on line 16 or 17 in /bot/commands/textHandler.js

**Comment by sleroq** [comment]
fixed in [`57dbd98`](https://github.com/iamdowner/nhentai-telegram-bot/commit/57dbd983b9fb35fac776c13c26692732542b163f)

**Comment by pseudokawaii** [comment]
> 
> 
> fixed in [`57dbd98`](https://github.com/iamdowner/nhentai-telegram-bot/commit/57dbd983b9fb35fac776c13c26692732542b163f)

Are you sure? i'm still having this issue even after redeploying the bot with the new code ~
https://i.imgur.com/YlMgoZc.gif

**Comment by sleroq** [comment]
@pseudokawaii
Have you updated the bot?
if you are using heroku:
https://dev.to/jessesbyers/how-to-update-a-deployed-app-on-heroku-3fde
https://stackoverflow.com/questions/28737548/how-to-update-an-heroku-app-created-using-github-deploy-to-heroku-button

**Comment by pseudokawaii** [comment]
@iamdowner I have manually deployed the master branch of [my own fork of this repo](https://github.com/pseudokawaii/nhentai-telegram-bot) which is 'even' with your main repo using heroku dashboard, you can even see the last build info on my [fork's environment](https://github.com/pseudokawaii/nhentai-telegram-bot/deployments?environment=nhentaiscraper#activity-log) ~

![image](https://user-images.githubusercontent.com/63403140/121785477-c3e87580-cbdb-11eb-97f6-010f86d5e7e9.png)

**Comment by sleroq** [comment]
ctx.botInfo was missing when using webhook
fixed by updating "telegraf"
